-- NACELUX Rev. 2.1 production baseline — PostgreSQL 16+
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TYPE member_role AS ENUM ('OWNER','ADMIN','MEMBER');
CREATE TYPE certainty AS ENUM ('OFFICIAL','VERIFIED','AI','INFERRED','PROBABLE','UNKNOWN');
CREATE TYPE job_status AS ENUM ('QUEUED','RUNNING','SUCCESS','FAILED','RETRY');
CREATE TYPE prospect_status AS ENUM ('NEW','QUALIFIED','CONTACTED','REPLIED','MEETING','CLIENT','LOST');

CREATE TABLE organizations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,slug text UNIQUE NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email citext UNIQUE NOT NULL,password_hash text,display_name text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE organization_members(organization_id uuid REFERENCES organizations ON DELETE CASCADE,user_id uuid REFERENCES users ON DELETE CASCADE,role member_role NOT NULL,PRIMARY KEY(organization_id,user_id));
CREATE TABLE subscription_plans(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text UNIQUE NOT NULL,name text NOT NULL,limits jsonb NOT NULL DEFAULT '{}');
CREATE TABLE subscriptions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,plan_id uuid NOT NULL REFERENCES subscription_plans,status text NOT NULL,starts_at timestamptz,ends_at timestamptz);
CREATE TABLE usage_records(id bigserial PRIMARY KEY,organization_id uuid NOT NULL REFERENCES organizations,metric text NOT NULL,quantity integer NOT NULL DEFAULT 1,recorded_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE data_sources(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,name text NOT NULL,source_type text NOT NULL,base_url text,status text NOT NULL,configuration jsonb NOT NULL DEFAULT '{}',last_run_at timestamptz);
CREATE TABLE raw_records(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,source_id uuid REFERENCES data_sources,external_id text,payload jsonb NOT NULL,checksum text,retrieved_at timestamptz NOT NULL,stage text NOT NULL DEFAULT 'RAW',UNIQUE(organization_id,source_id,external_id,checksum));
CREATE TABLE documents(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,source_id uuid REFERENCES data_sources,source_url text NOT NULL,storage_key text,document_type text,publication_date date,downloaded_at timestamptz,checksum text,download_status text,extraction_status text,UNIQUE(organization_id,checksum));

CREATE TABLE nace_versions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text UNIQUE NOT NULL,title text,valid_from date,source_url text,retrieved_at timestamptz);
CREATE TABLE nace_codes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),version_id uuid NOT NULL REFERENCES nace_versions,code text NOT NULL,level text NOT NULL,parent_code text,language char(2) NOT NULL,title text NOT NULL,description text,notes jsonb NOT NULL DEFAULT '{}',source_url text,retrieved_at timestamptz,UNIQUE(version_id,code,language));
CREATE TABLE nace_correspondences(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),source_version_id uuid REFERENCES nace_versions,target_version_id uuid REFERENCES nace_versions,source_code text,target_code text,relationship text,source_url text);
CREATE TABLE nacelux_categories(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,name text NOT NULL,slug text NOT NULL,UNIQUE(organization_id,slug));
CREATE TABLE nacelux_niches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,category_id uuid REFERENCES nacelux_categories,name text NOT NULL,slug text NOT NULL,attractiveness integer CHECK(attractiveness BETWEEN 0 AND 100),UNIQUE(organization_id,slug));
CREATE TABLE nacelux_subniches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,niche_id uuid REFERENCES nacelux_niches,name text NOT NULL,slug text NOT NULL,UNIQUE(organization_id,slug));

CREATE TABLE companies(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,company_name text NOT NULL,trade_name text,legal_form text,rcs_number text,vat_number text,creation_date date,status text,capital numeric,business_object text,description text,primary_nace_code text,secondary_nace_codes text[] NOT NULL DEFAULT '{}',category_id uuid REFERENCES nacelux_categories,niche_id uuid REFERENCES nacelux_niches,subniche_id uuid REFERENCES nacelux_subniches,website text,email text,phone text,country char(2) NOT NULL DEFAULT 'LU',canton text,municipality text,locality text,postal_code text,street text,street_number text,address_complement text,latitude numeric(9,6),longitude numeric(9,6),source_id uuid REFERENCES data_sources,source_url text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,rcs_number));
CREATE INDEX companies_org_nace_idx ON companies(organization_id,primary_nace_code);
CREATE INDEX companies_org_geo_idx ON companies(organization_id,municipality,locality,postal_code);
CREATE INDEX companies_org_creation_idx ON companies(organization_id,creation_date DESC);

CREATE TABLE company_classifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,company_id uuid NOT NULL REFERENCES companies ON DELETE CASCADE,classification_type text NOT NULL,code_or_taxonomy_id text NOT NULL,confidence numeric(4,3),method certainty NOT NULL,reasoning_summary text,is_primary boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE people(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,display_name text NOT NULL,source_type text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE company_people(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,company_id uuid NOT NULL REFERENCES companies ON DELETE CASCADE,person_id uuid NOT NULL REFERENCES people ON DELETE CASCADE,role text,job_title text,source_url text,confidence numeric(4,3),match_status text,method certainty NOT NULL);
CREATE TABLE digital_footprints(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,company_id uuid NOT NULL REFERENCES companies ON DELETE CASCADE,channel text NOT NULL,status text NOT NULL,source_url text,confidence numeric(4,3),checked_at timestamptz,details jsonb NOT NULL DEFAULT '{}',UNIQUE(organization_id,company_id,channel));
CREATE TABLE seo_audits(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,company_id uuid NOT NULL REFERENCES companies ON DELETE CASCADE,url text,seo_score integer CHECK(seo_score BETWEEN 0 AND 100),opportunity_score integer CHECK(opportunity_score BETWEEN 0 AND 100),findings jsonb NOT NULL DEFAULT '[]',status text NOT NULL,checked_at timestamptz);
CREATE TABLE business_signals(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,company_id uuid NOT NULL REFERENCES companies ON DELETE CASCADE,signal_type text NOT NULL,signal_value jsonb,confidence numeric(4,3),source text,detected_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE opportunity_scores(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,company_id uuid NOT NULL REFERENCES companies ON DELETE CASCADE,score integer NOT NULL CHECK(score BETWEEN 0 AND 100),level text NOT NULL,breakdown jsonb NOT NULL,recommended_action text,model_version text NOT NULL,calculated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX opportunity_org_score_idx ON opportunity_scores(organization_id,score DESC);
CREATE TABLE prospects(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,company_id uuid NOT NULL REFERENCES companies,owner_id uuid REFERENCES users,assigned_to uuid REFERENCES users,status prospect_status NOT NULL DEFAULT 'NEW',priority text,notes text,next_action text,next_action_date date,last_contacted_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(organization_id,company_id));

CREATE TABLE jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,job_type text NOT NULL,status job_status NOT NULL DEFAULT 'QUEUED',schedule text,payload jsonb NOT NULL DEFAULT '{}',attempt integer NOT NULL DEFAULT 0,started_at timestamptz,finished_at timestamptz,error text);
CREATE TABLE data_lineage(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid NOT NULL REFERENCES organizations,entity_type text NOT NULL,entity_id uuid NOT NULL,field_name text NOT NULL,source_id uuid REFERENCES data_sources,source_url text,document_id uuid REFERENCES documents,retrieved_at timestamptz NOT NULL,confidence numeric(4,3),method certainty NOT NULL);
CREATE TABLE audit_logs(id bigserial PRIMARY KEY,organization_id uuid NOT NULL REFERENCES organizations,user_id uuid REFERENCES users,action text NOT NULL,entity_type text,entity_id uuid,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());

-- Apply the same policy to every organization-owned table in deployment migrations.
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_companies ON companies USING (organization_id = current_setting('app.organization_id',true)::uuid) WITH CHECK (organization_id = current_setting('app.organization_id',true)::uuid);
