-- NACELUX Rev. 2.1 — PostgreSQL/Supabase baseline
-- Additive and idempotent: no DROP, TRUNCATE, or destructive ALTER statements.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS organizations(id text PRIMARY KEY,name text NOT NULL,slug text UNIQUE,created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS users(id text PRIMARY KEY,email text UNIQUE NOT NULL,display_name text,created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS organization_members(organization_id text NOT NULL REFERENCES organizations(id),user_id text NOT NULL REFERENCES users(id),role text NOT NULL CHECK(role IN('OWNER','ADMIN','MEMBER')),PRIMARY KEY(organization_id,user_id));
CREATE TABLE IF NOT EXISTS companies(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),company_name text NOT NULL,trade_name text,legal_form text,rcs_number text,vat_number text,creation_date date,status text,capital numeric,business_object text,description text,primary_nace_code text,secondary_nace_codes jsonb,category text,niche text,subniche text,website text,email text,phone text,country text DEFAULT 'LU',canton text,municipality text,locality text,postal_code text,street text,street_number text,address_complement text,latitude double precision,longitude double precision,website_status text DEFAULT 'NOT_CHECKED',digital_score integer,seo_score integer,seo_opportunity integer,google_status text DEFAULT 'NOT_CHECKED',decision_maker_status text DEFAULT 'UNKNOWN',niche_attractiveness integer DEFAULT 50,commercial_potential integer DEFAULT 50,source_status text DEFAULT 'UNKNOWN',source_name text,source_url text,is_demo boolean DEFAULT false,created_at timestamptz NOT NULL,updated_at timestamptz NOT NULL,UNIQUE(organization_id,rcs_number));
CREATE INDEX IF NOT EXISTS idx_company_tenant ON companies(organization_id);
CREATE INDEX IF NOT EXISTS idx_company_geo ON companies(organization_id,municipality,postal_code);
CREATE INDEX IF NOT EXISTS idx_company_nace ON companies(organization_id,primary_nace_code);
CREATE INDEX IF NOT EXISTS idx_company_created ON companies(organization_id,creation_date);
CREATE TABLE IF NOT EXISTS business_signals(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),company_id text NOT NULL REFERENCES companies(id),signal_type text,signal_value jsonb,confidence double precision,source text,detected_at timestamptz);
CREATE TABLE IF NOT EXISTS opportunity_scores(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),company_id text NOT NULL REFERENCES companies(id),score integer CHECK(score BETWEEN 0 AND 100),level text,breakdown jsonb NOT NULL DEFAULT '[]',recommended_action text,calculated_at timestamptz,UNIQUE(organization_id,company_id));
CREATE INDEX IF NOT EXISTS idx_opp_score ON opportunity_scores(organization_id,score DESC);
CREATE TABLE IF NOT EXISTS prospects(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),company_id text NOT NULL REFERENCES companies(id),status text,priority text,owner text,assigned_to text,notes text,next_action text,next_action_date date,last_contacted_at timestamptz,created_at timestamptz,updated_at timestamptz,UNIQUE(organization_id,company_id));
CREATE TABLE IF NOT EXISTS data_sources(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),name text,source_type text,base_url text,status text,last_run_at timestamptz,records_count integer DEFAULT 0,note text);
CREATE TABLE IF NOT EXISTS jobs(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),job_type text,status text,started_at timestamptz,finished_at timestamptz,records_processed integer DEFAULT 0,error text);
CREATE TABLE IF NOT EXISTS data_lineage(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),entity_type text,entity_id text,field_name text,source_id text,source_url text,document_id text,retrieved_at timestamptz,confidence double precision,method text);
CREATE TABLE IF NOT EXISTS audit_logs(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),user_id text,action text,entity_type text,entity_id text,metadata jsonb NOT NULL DEFAULT '{}',created_at timestamptz);
CREATE TABLE IF NOT EXISTS nace_codes(id text PRIMARY KEY,version text NOT NULL,code text NOT NULL,level text NOT NULL,title_fr text,title_de text,title_en text,parent_code text,includes_text text,excludes_text text,source_status text,source_url text,is_demo boolean DEFAULT true,UNIQUE(version,code));
CREATE TABLE IF NOT EXISTS taxonomy_nodes(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),node_type text NOT NULL,parent_id text REFERENCES taxonomy_nodes(id),name text NOT NULL,slug text,attractiveness integer DEFAULT 50,is_active boolean DEFAULT true,UNIQUE(organization_id,node_type,slug));
CREATE TABLE IF NOT EXISTS people(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),display_name text NOT NULL,job_title text,company_id text REFERENCES companies(id),profile_url text,source_type text,match_status text,confidence double precision,is_demo boolean DEFAULT true,created_at timestamptz);
CREATE TABLE IF NOT EXISTS digital_checks(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),company_id text NOT NULL REFERENCES companies(id),channel text,status text,source_url text,confidence double precision,checked_at timestamptz,details jsonb NOT NULL DEFAULT '{}',UNIQUE(organization_id,company_id,channel));
CREATE TABLE IF NOT EXISTS seo_audits(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),company_id text NOT NULL REFERENCES companies(id),url text,status text,seo_score integer,opportunity_score integer,findings jsonb NOT NULL DEFAULT '[]',checked_at timestamptz,UNIQUE(organization_id,company_id));
CREATE TABLE IF NOT EXISTS resa_publications(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),publication_number text,publication_date date,entry_type text,company_name text,rcs_number text,source_url text,document_url text,download_status text,extraction_status text,change_status text,source_status text,is_demo boolean DEFAULT true,created_at timestamptz);
CREATE TABLE IF NOT EXISTS reports(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),report_type text,title text,status text,format text,entity_id text,created_at timestamptz,completed_at timestamptz);
CREATE TABLE IF NOT EXISTS territories(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),name text NOT NULL,description text,municipalities jsonb,center_lat double precision,center_lng double precision,radius_km double precision,created_at timestamptz);
CREATE TABLE IF NOT EXISTS scoring_weights(id text PRIMARY KEY,organization_id text NOT NULL REFERENCES organizations(id),factor text NOT NULL,weight integer NOT NULL CHECK(weight BETWEEN 0 AND 100),updated_at timestamptz,UNIQUE(organization_id,factor));
CREATE TABLE IF NOT EXISTS schema_migrations(version text PRIMARY KEY,checksum text NOT NULL,applied_at timestamptz NOT NULL DEFAULT now());
